### ISSUE TITLE
Error in grDevices::dev.off()

### ISSUE THREAD

**Issue by fidibidi** [e-jorsboe/fastNGSadmix#8] opened 2023-04-06 17:30 UTC
Hello!

Just wanted to note, there appears to be an incompatibility issue when using new versions of R with some of the R scripts... 

So far 2 programs I've tried using, makeBarPlot and fastNGSadmixPCA, both give me the following error:

Error in grDevices::dev.off() :
  cannot shut down device 1 (the null device)
Execution halted

My version of R is 4.0.2. 
I'm not super familiar with R, but I think its because the grDevices package doesn't seem to be compatible or present in this version... 

I've bypassed this issue by removing any line that calls this package.

fastNGSadmix is great!

**Comment by e-jorsboe** [comment] 2023-04-11 14:53
Hi,

The issue is caused by opening the palette `(grDevices::palette(ccol)),` for some reason this creates a plot window, that needs to be removed - hence `dev.off()`. However, on some systems this plot window is not created, and when one tries to close it - one gets an error like you! I have included some commands so this should not happen, and also no plot window is created.

Please re-clone the aforementioned files and try and run it again, and let me know if that helped?

**Closed as completed** 2023-04-13 14:09 UTC
